# syntax=docker/dockerfile:1
# check=error=true

# This Dockerfile is designed for production, not development. Use with Kamal or build'n'run by hand:
# docker build -t abcd .
# docker run -d -p 80:80 -e RAILS_MASTER_KEY=<value from config/master.key> --name abcd abcd

# For a containerized dev environment, see Dev Containers: https://guides.rubyonrails.org/getting_started_with_devcontainer.html

# Make sure RUBY_VERSION matches the Ruby version in .ruby-version
ARG RUBY_VERSION=3.4.2
FROM docker.io/library/ruby:$RUBY_VERSION-slim AS base

ARG USER_ID=1000
ARG GROUP_ID=1000

RUN apt-get update && apt-get install -y \
  libyaml-dev \
  libgmp-dev \
  libreadline-dev \
  build-essential \
  nodejs \
  libjemalloc2 \
  libvips \
  sqlite3 \
  watchman \
  pkg-config \
  git \
  libsqlite3-dev \
  sudo \
  libpq-dev \
  postgresql-client \
  imagemagick \
  libmagickwand-dev \
  && rm -rf /var/lib/apt/lists /var/cache/apt/archives

RUN groupadd -g ${GROUP_ID} appuser && useradd -u ${USER_ID} -g ${GROUP_ID} -m appuser

RUN echo "appuser ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

USER appuser

WORKDIR /app
COPY --chown=appuser:appuser Gemfile* ./
RUN gem install bundler
RUN bundle lock --add-platform x86_64-linux
RUN bundle install
RUN gem install foreman
COPY --chown=appuser:appuser . /app
RUN sudo rm -rf tmp/*
ADD . /app
