default: &default
  store_options:
    max_age: <%= 60.days.to_i %>
    namespace: <%= Rails.env %>
  size_estimate_samples: 1000

development:
  <<: *default
  database: cache

production:
  <<: *default
  database: cache
  store_options:
    namespace: "production_cache"
    max_entries: 100000
