service: foolkgs_testing_board_control
image: foolkgs/board_control_kamal2
servers:
  web:
  - 3.148.252.131

ssh:
  user: ubuntu
  keys: [ "~/.ssh/rtoledo-dev-aws.pem" ]

registry:
  server: docker.io
  username:
  - DOCKER_USERNAME
  password:
  - DOCKER_PASSWORD

builder:
  arch: "amd64"
  dockerfile: Dockerfile
  context: .
  args:
    RUBY_VERSION: "3.2"

env:
  clear:
    DATABASE_URL: "postgresql://${AWS_DB_USER}:${AWS_DB_PASSWORD}@${AWS_DB_HOST}:${AWS_DB_PORT}/${AWS_DB_NAME}"
    RAILS_STORAGE: s3
    AWS_REGION: us-east-2
    AWS_BUCKET: rtoledo-rails
    DOCKER_TOKEN: ${DOCKER_HUB_TOKEN}
    DOCKER_USER: ${DOCKER_USER}
    DOCKER_PASSWORD: ${DOCKER_PASSWORD}
    JWT_KEY: ${JWT_KEY}
  secret:
  - RAILS_MASTER_KEY

volumes:
- "storage:/app/storage"
