service: rtoledo_testing_board_control
image: rtoledo/board_control_kamal2
# default: &default
#   image: rtoledo/board_control_kamal2
#   ssh:
#     user: ubuntu
#     keys: [ "~/.ssh/rtoledo-dev-aws.pem" ]
#   env:
#     clear:
#       RAILS_ENV: <%= ENV['KAMAL_ENV'] || 'production' %>
#       RAILS_STORAGE: s3
#       AWS_REGION: us-east-2
#       AWS_BUCKET: rtoledo-rails
#   registry:
#     server: docker.io
#     username: foolkgs
#     password:
#     - KAMAL_REGISTRY_PASSWORD
#     secret:
#     - RAILS_MASTER_KEY
#     - SECRET_KEY_BASE
#   builder:
#     arch: "amd64"
#     dockerfile: Dockerfile
#     context: .
#     args:
#       RUBY_VERSION: "3.2.1"


#   production:
#     <<: *default
#     hosts:
#     - 3.148.252.131
#     env:
#   clear:
#     DATABASE_URL: "postgresql://${AWS_DB_USER}:${AWS_DB_PASSWORD}@${AWS_DB_HOST}:${AWS_DB_PORT}/${AWS_DB_PRODUCTION_NAME}"
#     labels:
#       traefik.http.routers.prod.rule: Host('rails_production.rtoledo.inf.br')
#       traefik.http.routers.prod.tls: true
#     volumes:
#     - "storage:/app/storage"
#   staging:
#     <<: *default
#     hosts:
#     - 10.0.0.1
#     env:
#       clear:
#         RAILS_ENV: staging
#         DATABASE_URL: "postgresql://${AWS_DB_USER}:${AWS_DB_PASSWORD}@${AWS_DB_HOST}:${AWS_DB_PORT}/${AWS_DB_STAGING_NAME}"
#     labels:
#       traefik.http.routers.prod.rule: Host('rails_staging.rtoledo.inf.br')
#     volumes:
#     - "storage:/app/storage"
servers:
  web:
  - 3.148.252.131

ssh:
  user: ubuntu
  keys: [ "~/.ssh/rtoledo-dev-aws.pem" ]

registry:
  server: docker.io
  username:
  - DOCKER_USER
  password:
  - DOCKER_PASSWORD

builder:
  arch: "amd64"
  dockerfile: Dockerfile
  context: .
  args:
    RUBY_VERSION: "3.2.1"

env:
  clear:
    DATABASE_URL: "postgresql://${AWS_DB_USER}:${AWS_DB_PASSWORD}@${AWS_DB_HOST}:${AWS_DB_PORT}/${AWS_DB_NAME}"
    RAILS_STORAGE: s3
    AWS_REGION: us-east-2
    AWS_BUCKET: rtoledo-rails
    DOCKER_TOKEN: ${DOCKER_HUB_TOKEN}
    DOCKER_USER: ${DOCKER_USER}
    DOCKER_PASSWORD: ${DOCKER_PASSWORD}
  secret:
  - RAILS_MASTER_KEY

volumes:
- "storage:/app/storage"
